import { AssDialogueFormat, AssStyleFormatV4 } from '../interface/subtitle'
const DEFAULT_META = `[Script Info]
; Script generated by Aegisub 3.2.2
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: None

[Aegisub Project Garbage]
Active Line: 1`

const DEFAULT_SCRIPT_STYLE = `
[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style:`

const DEFAULT_SCRIPT_DIALOGUE = `
[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`

export function generateScriptInfo(scriptStyle: AssStyleFormatV4): string {
  let scriptInfo = DEFAULT_META

  scriptInfo += '\n' + DEFAULT_SCRIPT_STYLE
  scriptInfo += `${scriptStyle.name},${scriptStyle.fontName},${scriptStyle.fontSize},${scriptStyle.primaryColor},${scriptStyle.secondaryColor},${scriptStyle.outlineColor},${scriptStyle.backColor},${scriptStyle.bold},${scriptStyle.italic},${scriptStyle.underline},${scriptStyle.strikeout},${scriptStyle.scaleX},${scriptStyle.scaleY},${scriptStyle.spacing},${scriptStyle.angle},${scriptStyle.borderStyle},${scriptStyle.outline},${scriptStyle.shadow},${scriptStyle.alignment},${scriptStyle.marginL},${scriptStyle.marginR},${scriptStyle.marginV},${scriptStyle.encoding}`

  return scriptInfo
}

export function generateDialogues(dialogues: AssDialogueFormat[]): string {
  let dialogueText = '\n' + DEFAULT_SCRIPT_DIALOGUE

  for (const dialogue of dialogues) {
    dialogueText += `Dialogue: ${dialogue.layer},${dialogue.start},${dialogue.end},${dialogue.style},${dialogue.name},${dialogue.marginL},${dialogue.marginR},${dialogue.marginV},${dialogue.effect},${dialogue.text}\n`
  }

  return dialogueText
}
